apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 47.1.0
    chart: kube-prometheus-stack
    helm:
      valueFiles:
        - $values/gitops/observability/prometheus-stack/values.yaml
  - repoURL: https://github.com/leohauschild/devops_project.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true

