apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-pass
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAO/1sNDoWII+85zeMFE5HiLMQU2d8P0qudD+/hVeDoclClXxwWxgtyeOmakkvv9Ft24Tc56vIxgVsURphCX8kaS5KAuz0bZy6PzF+pGTDQoLhdLEPFlv4uyqhSUfJa1IwXKOcenKcQoTnhgS41R1UHQdsoM7IlL/ZoIUc9u19IfY+KmWqd/10LztG0M/TjtDR+l62j9a7g/WNc7VZA1aPLhXj3hpgtncSxg+JBhWfe6pTNs6dwO6+NW1enQWLd7IpRePHhaHYSTolpTYK90aBuvkOdVKn+eXDi9nghBWnx1XLVSJH5McwC9Wd96fC6q9twpP/jzyNaylzaajicf6EWw52OcyC/AI37jdUrqRWcq9deZ+x2DS3u0PdY8q/b+W1pAV5qcJxf3Ki+k3e39qeCWOlGiG4PRCtxlLcrSj07CRVhKJbli9PPlWdguubItTkTvXtft+kqxpfDv/j7XhEob0OPgqiwuodMlt5Xh9GKAWD0c/1+pqGI3iC6gilrAcJ7swRzwFzUoTldFCCt5GzutIzGnkHc53KaWr8FUbV+N7SRfli+CE6QOio9TMrVueibdOaBW4/52M1+Q1ZX7FEiQTQ+qpllRfVKg2dprDldtJpuZK75zkE9Kct8oft6YGf0JCU4kLCDTWODXivHp7XH6FWucAVPFN3/JuAks4GORmK8sx7lYfC6YnxG+ZubAQeXOEBB4P5i3Q==
    admin-user: AgAPnORt7gol5TJbAicsk2uzQYY4R01OUFDKxxixbwlyCR+D7vIfnLi/RZYNAYJXPFlAX3Z+NXaZYDmMDEfRiz5MzTBu0OZq0wikuZhu559AkOoXMVBGJUyv2AKFR4anq4xXlzrPvwPWH9sA92MlnqL6GpQnHYJkWIP0embpBK+8uCr2odmMjnEx+KMUhICqYvORChe3ewhcKpRslDGTPW8bQJxVsYXcQYuz1vBO6THAPUWFZfXDi7cjV2kOWFbe01/Wpi/M+eaJiFVlF9xn21z/8OXew1IGTYQQoQlnEBA2TmAUkN3A0TUtwXVAeZQ82rIsCPXkrknfQGNxzil77qLpHBC/Sdx7yQpt347OjN9sF05fEpTbZUWxjDUBV8rXhbEpGn8KiiTovRMbYVnSP2iODISdAhqRBIGH7ePLrYDlTwZhgJyikjutsb2PeOKTG50UmDa23CJBqf4mmIUKXRjza++4s8EjLPegSXEYkQn5U8urwJyfbRp1uJa8qI/8XOgXSMY9pSyb/fExRiuRd6HtImUVJSlY26ejzYCMdmqcnlL/srtpKsVgeFxw2AXrQ7BLcysYZffG+5aABjPmVa1YP9YIspk1Z793cGgWYZVXrRtx4wVPvAAsZRItV8WHF0V7TjpXNzFBrmEf4OkAOfskkloCzyk3UjGXVlX8YLxFaYIEr0nVz4FeoWQ+rRaWQ+aomPGgLg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-pass
      namespace: observability

