apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.6.0
    chart: ingress-nginx
    helm:
      valueFiles:
        - $values/gitops/ingress-nginx/values.yaml
  - repoURL: https://github.com/leohauschild/devops_project.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
