apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: voting-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leohauschild/devops_project.git
    targetRevision: HEAD
    path: voting-app-yaml-files
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # If true the changes made on live cluster will not be maintained 
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true